title:              MalWhere? Reports 
email:              jasongocotano@gmail.com
description:        A specialized blog dedicated to the in-depth exploration of malware analysis, reverse engineering, and cybersecurity research. Whether you're a seasoned analyst, a cybersecurity student, or a curious tech enthusiast, this blog offers a wealth of knowledge to help you understand the inner workings of malicious software.
author:             Kriticko29
baseurl:            "/MalWhere?"
url:                "https://kriticko29.github.io"

# Social Profiles
twitter_username:   cjgeollegue
github_username:    Kriticko29
facebook_username:  Cjgeollegue
instagram_username:  CjGeollegue
linkedin_username:  Cjgeollegue

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
